project_id = "hxsykzhergwulxsayckj"

[functions.generate-bio]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.verify-magic-link]
verify_jwt = false

[functions.check-admin]
verify_jwt = false

[functions.delete-profile]
verify_jwt = false

[functions.profile-meta]
verify_jwt = false

[functions.sync-events]
verify_jwt = false

[functions.send-sponsorship-inquiry]
verify_jwt = false
